docs(app): Add Atom IDE setup
b2io/development-standards pull request #11
Opened 2017-04-06 18:20 UTC by reeddunkle

- added Atom IDE setup

Closes #10

2017-04-06 18:49 UTC, chawkins-nj commented on ide/atom/README.md
> +## Packages
Are we going to update this every time this list changes/updates? Maybe we should leave off the version numbers and/or only list the packages that we all use that aren't already installed by default?

2017-04-06 18:55 UTC, chriswhawkins commented on ide/atom/README.md
> +- react@0.16.2
A couple of others that I have in my list that are kind of handy:
- atom-beautify (@0.29.17)
- pigments (@0.39.1)
- tabs-to-spaces (@1.0.3)

2017-04-06 18:55 UTC, chriswhawkins commented on ide/atom/README.md
> +## Packages
☝️ suspicious non-member

2017-04-06 18:57 UTC, chriswhawkins commented on ide/atom/README.md
> +- Struggles with large JSON files (60k lines)
Struggles with large files period in my experience

2017-04-06 18:57 UTC, chriswhawkins approved these changes
Couple of comments to chew on... Looks good. Appreciate you doing this kind of stuff!

2017-04-18 12:37 UTC, tborres requested changes
Looks great. Some suggested changes to the shortcuts and then it's ready to go.

2017-04-18 12:37 UTC, tborres commented on ide/atom/README.md
> +- [Mac](./mac.md)
Should probably have a single page of shortcuts that displays the shortcut keys for mac and windows.

2017-04-18 12:37 UTC, tborres commented on ide/atom/mac.md
> +## Duplicate selection: <kbd>⌘</kbd><kbd>d</kbd>
👍 I actually never use this shortcut, but I need to start.

It's <kbd>ctrl</kbd><kbd>d</kbd> in windows

2017-04-18 12:37 UTC, tborres commented on ide/atom/mac.md
> +## Duplicate line: <kbd>⌘</kbd><kbd>Shift</kbd><kbd>d</kbd>
It's <kbd>ctrl</kbd><kbd>shift</kbd><kbd>d</kbd> in windows

2017-04-18 12:37 UTC, tborres commented on ide/atom/mac.md
> +## Open Project File: <kbd>⌘</kbd><kbd>Shift</kbd><kbd>t</kbd>, also <kbd>⌘</kbd><kbd>Shift</kbd><kbd>p</kbd>
Windows: <kbd>ctrl</kbd><kbd>t</kbd> or <kbd>ctrl</kbd><kbd>p</kbd>

2017-04-18 12:37 UTC, tborres commented on ide/atom/mac.md
> +## Move selected line(s) up and down: <kbd>⌘</kbd><kbd>Ctrl</kbd><kbd>↑</kbd>/<kbd>↓</kbd>
Windows: <kbd>ctrl</kbd><kbd>↑</kbd><kbd>ctrl</kbd><kbd>↓</kbd>

2017-04-18 12:37 UTC, tborres commented on ide/atom/mac.md
> +- Split panes
Windows: <kbd>ctrl</kbd><kbd>k</kbd> and then arrow in the direction to split (e.g. <kbd>→</kbd>)

2017-04-18 12:37 UTC, tborres commented on ide/atom/mac.md
> +- Toggle tree view(?) (left side project explorer)
Windows: <kbd>ctrl</kbd><kbd>\\</kbd>

2017-04-18 14:24 UTC, merged